### ISSUE TITLE
Reading not working

### ISSUE THREAD

**Issue by mohammadms2008** [madhead/read-java-properties#38]
hello. when I use this action in my project, I got this error.

![image](https://user-images.githubusercontent.com/18048394/185920477-0c21f260-7b55-40fe-b713-e0cafe6898fa.png)

This is my code:

```
      - uses: madhead/read-java-properties@latest
        id: all
        with:
          file: gradle.properties
          all: true          
```

how can I fix it ???

**Comment by madhead** [comment]
Well, @mohammadms2008, most probably, there is no `gradle.properties` file **in the root of your project**. Double-check it's location. Make sure it's committed at all.

**Comment by mohammadms2008** [comment]
so disappointing answer, buddy. I'm not android beginner and I certainly know where `gradle.properties` must be...

**Comment by madhead** [comment]
If you're not a beginner, then you definitely know what a `java.io.FileNotFoundException` is. Look, I'm not doing any magic here, the code is absolutely straightforward:

https://github.com/madhead/read-java-properties/blob/88d0f7bdc0e1e5d1b7fbc89436743079dccf6931/src/main/kotlin/me/madhead/github/actions/rjp/ReadJavaProperties.kt#L12-L17

And this piece throws an `FileNotFoundException`. Something wrong with your CI setup. The file is just not there. Or the path (`gradle.properties`) is wrong. It works for me and some other users.

Double check your CI. Consider taking a look at the tests in this repository: https://github.com/madhead/read-java-properties/blob/master/.github/workflows/test.yml. They are passing.

**Comment by madhead** [comment]
Here, I demonstrate it to you, @mohammadms2008

This run (https://github.com/madhead/read-java-properties-38/runs/8122860080?check_suite_focus=true) failed with the same exception that you have, because the file is missing.

This run (https://github.com/madhead/read-java-properties-38/runs/8122870432?check_suite_focus=true) passed. Because the file is there. I [committed](https://github.com/madhead/read-java-properties-38/commit/dc52bec6a2f64fdf8be67005b690b7aecf4eb9f1) it.

Here is the workflow config: https://github.com/madhead/read-java-properties-38/blob/main/.github/workflows/test.yml.

Take a look.

**Comment by mohammadms2008** [comment]
the `gradle.properties` absoultely exists in the project and let's don't discuss about it.

![screenshot](https://user-images.githubusercontent.com/18048394/188271035-6f20cac2-f423-4caf-ad89-da425619bef7.JPG)

and these are the properties I want to read using your action:

![screenshot1](https://user-images.githubusercontent.com/18048394/188271177-4137a648-a064-4ded-ba5b-b3554bb8f0ca.JPG)

Thanks for your example. It works fine. even I tested for my own properties in `gradle.properties` and it worked, so the `gradle.properties` exist in my project.. 
I want to generate signed apk file for any companies that bought my app and I also want to name every apk to name of company and version name provided in `gradle.properties`
I used your action in my code and I got the error I sent before.

```
name: Generate signed APK for each company

on: workflow_dispatch

jobs:
  build:
  
    strategy:
      matrix:
        companyName: ["borhanbs.ir", "dpedu.ir", "dpe.ac", "pnudp.com"]

    runs-on: ubuntu-latest

    steps:
    
      - uses: madhead/read-java-properties@latest
        id: all
        with:
          file: gradle.properties
          all: true          
          
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Access COMPANY_NAME
        env:
          COMPANY_NAME: ${{ matrix.companyName }}
        run: echo COMPANY_NAME=\"$COMPANY_NAME\" > ./local.properties
      
      - name: Build APK
        id: build
        run: bash ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.all.outputs.VERSION_NAME }}_${{ matrix.companyName }}
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
```


How do you think about it???

**Comment by madhead** [comment]
I think, @mohammadms2008, you should swap `read-java-properties` and `checkout` action. You should check out repository first:

![image](https://user-images.githubusercontent.com/577360/188277172-7233604d-6a48-48f8-864b-22bb11b4c198.png)

Unless you do a checkout the working directory is empty. It means, there are no files in it. Not a single file is there. Including the `gradle.properties`. They unexist before you checkout.

**Comment by madhead** [comment]
See, [in the example](https://github.com/madhead/read-java-properties-38/blob/main/.github/workflows/test.yml) `actions/checkout` comes before `madhead/read-java-properties`:

```yml
      - uses: actions/checkout@v3


      - uses: madhead/read-java-properties@latest
        id: all
        with:
          file: gradle.properties
          all: true     
```
